# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Cryptol and Saw Python Clients

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Typecheck with mypy
    #   run: |
    #     python -m mypy cryptol saw
    # FIXME - currently cryptol server requires a restart between tests as starting from the
    # initial server state in a request does _not_ seem to restart the working directory of
    # the server.
    - name: Launch Cryptol Server
      run: |
        docker run --name=cryptol-remote-api -d \
          -v $PWD/tests/cryptol/test-files:/tests/cryptol/test-files \
          -p 8080:8080 \
          ghcr.io/galoisinc/cryptol-remote-api:nightly-portable
    - name: Test Cryptol Bitvector lib
      run: |
        python -m unittest tests/cryptol/test_bitvector.py
    - name: Test Cryptol low-level remote API
      run: |
        python -m unittest tests/cryptol/test_low_level_ops.py
      env:
        CRYPTOL_SERVER_URL: "http://localhost:8080/"
    - name: Test Cryptol remote API
      run: |
        docker restart cryptol-remote-api
        python -m unittest tests/cryptol/test_cryptol_api.py
      env:
        CRYPTOL_SERVER_URL: "http://localhost:8080/"

    # - name: Unittest Cryptol (eval) client/server
    #   run: |
    #     python -m unittest discover tests/cryptol_eval
    # - name: Unittest SAW remote client/server
    #   run: |
    #     python -m unittest discover tests/saw
